language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.travis
matrix:
  allow_failures:
    - rvm: 2.0.0
services:
  - mongodb
  - elasticsearch
env: ELASTICSEARCH_INDEX_URL=http://localhost:9200/
script: "bundle exec rake test:all"
notifications:
  irc: "irc.freenode.org#rstatus"
